-- Seed: agency packages (Paket Full Funnel).
-- Note: This seed only touches `public.agency_packages`.

insert into public.agency_packages (
  id, slug, sort_order, is_published,
  badge_label, title, package_label, summary,
  strikethrough_price, price,
  promo_marquee_text, footer_note, footer_extra_html,
  show_best_seller, best_seller_image_path, best_seller_image_url, badge_image_path, badge_image_url,
  promo_countdown_ends_at, footer_countdown_label, show_footer_countdown,
  spent_budget_min, spent_budget_max, spent_budget_currency, spent_budget_period,
  fee_percent,
  sections
) values
  (
    '55555555-5555-4555-8555-000000000001'::uuid,
    'fullfunnel_starter',
    30,
    true,
    'Paket Full Funnel',
    'Full Funnel Starter',
    'Full Funnel Starter',
    'Ads + landing + content dasar + reporting (single offer).',
    'Rp 20.000.000',
    'Rp 15.000.000',
    'Termasuk content planning & copy (tanpa produksi video/foto on-site).',
    'Ad spend dibayar langsung ke platform. Produksi foto/video on-site = add-on.',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    10000000,
    50000000,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"strategy","title":"Strategy & KPI","intro":"Satu arah yang jelas.","bullets":["KPI utama (CPL/CPA) + guardrail","Roadmap 30 hari","Prioritas channel"]},
      {"id":"ads","title":"Ads Management","intro":"Testing + optimasi rutin.","bullets":["Structure campaign (cold/warm/retarget)","Optimasi weekly","Creative request & review"]},
      {"id":"content","title":"Content (Included)","intro":"Konten untuk support iklan & trust.","bullets":["Kalender konten 4 minggu","12 ide konten/bulan","Copy/caption + CTA siap pakai","2 script reels/shorts (opsional)"]},
      {"id":"landing","title":"Landing Page (CRO-ready)","intro":"Fokus ke conversion.","bullets":["1 landing page (atau audit LP existing)","Rekomendasi CRO prioritas","Tracking event (view/lead)"]},
      {"id":"tracking","title":"Tracking & Dashboard","intro":null,"bullets":["Pixel/GA + UTM","Dashboard KPI ringkas","Eksperimen log (basic)"]},
      {"id":"report","title":"Reporting","intro":null,"bullets":["Weekly update","Monthly recap + plan","Rekomendasi ad spend: IDR 10.000.000–50.000.000 / bulan"]} 
    ]$pkg$::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000002'::uuid,
    'fullfunnel_growth',
    31,
    true,
    'Paket Full Funnel',
    'Full Funnel Growth',
    'Full Funnel Growth',
    'Full funnel + content system + CRO plan (eksekusi lebih rapat).',
    'Rp 35.000.000',
    'Rp 25.000.000',
    'Termasuk content system (script/caption/template) + creative review rutin.',
    'Ad spend dibayar langsung ke platform. Produksi foto/video on-site = add-on.',
    null,
    true,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    50000000,
    150000000,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"strategy","title":"Strategy & Offer","intro":"Selaras dengan target bisnis.","bullets":["Persona + offer breakdown","Angle matrix + messaging","Roadmap 30–60 hari"]},
      {"id":"ads","title":"Ads Management (Advanced)","intro":"Scale bertahap dengan guardrail.","bullets":["Multi-campaign structure","Budget rebalancing mingguan","Monitoring lebih rapat"]},
      {"id":"content","title":"Content System (Included)","intro":"Supply creative stabil & terukur.","bullets":["Kalender konten 4 minggu","20 ide konten/bulan","10 script reels/shorts","Caption + CTA + objection handling","Template desain basic (opsional)"]},
      {"id":"creative","title":"Creative System","intro":"Brief, review, dan iterasi yang rapi.","bullets":["Creative cadence terjadwal","Brief & review terstruktur","Library winners/losers","Guideline hook/angle per persona"]},
      {"id":"landing","title":"Landing & CRO","intro":"Optimasi conversion rate.","bullets":["Audit LP/WA/form","Eksperimen CRO prioritas","Tracking per step (opsional)"]},
      {"id":"tracking","title":"Tracking & Insight","intro":null,"bullets":["Event mapping lebih lengkap","Dashboard KPI + breakdown","Eksperimen log (hypothesis → result)"]},
      {"id":"report","title":"Reporting","intro":null,"bullets":["Weekly review","Monthly recap + forecast","Action plan 30 hari","Rekomendasi ad spend: IDR 50.000.000–150.000.000 / bulan"]} 
    ]$pkg$::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000003'::uuid,
    'fullfunnel_scale',
    32,
    true,
    'Paket Full Funnel',
    'Full Funnel Scale (Ops-ready)',
    'Full Funnel Scale (Ops-ready)',
    'Full funnel scale: multi-channel + content engine + monitoring harian.',
    'Rp 55.000.000',
    'Rp 40.000.000',
    'Content engine included + ops/monitoring harian untuk scale besar.',
    'Ad spend dibayar langsung ke platform. Produksi foto/video on-site = add-on.',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    150000000,
    500000000,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"strategy","title":"Strategy & Growth System","intro":"Sistem supaya scale terkontrol.","bullets":["Growth model + guardrail","Eksperimen backlog + schedule","Roadmap 60–90 hari"]},
      {"id":"ops","title":"Ops & Monitoring","intro":"Kontrol harian untuk scale besar.","bullets":["Monitoring harian (guardrail)","Incident response (spend spike/drop)","Checklist issue (tracking/learning/budget)"]},
      {"id":"ads","title":"Ads & Budgeting","intro":"Scale multi-channel sesuai data.","bullets":["Channel expansion (Meta/TikTok/Google)","Budget allocation + rebalancing","Retargeting & LTV focus"]},
      {"id":"content","title":"Content Engine (Included)","intro":"Volume dan iterasi lebih tinggi.","bullets":["Kalender konten 4 minggu + backlog","30 ide konten/bulan","16 script reels/shorts","Caption + CTA + keyword set","Template produksi/editing guideline (opsional)"]},
      {"id":"creative","title":"Creative Engine","intro":"Creative pipeline untuk scale.","bullets":["Cadence lebih padat","Angle matrix + iterasi cepat","Quality control","Creative review 2x/minggu"]},
      {"id":"funnel","title":"Funnel & CRO","intro":"Maksimalkan conversion supaya CPA turun.","bullets":["Audit funnel per step","CRO sprint plan + prioritas","Quality feedback loop (sales/CS)"]},
      {"id":"tracking","title":"Tracking Advanced","intro":null,"bullets":["Event mapping per step","Dashboard KPI + cohort sederhana (opsional)","Eksperimen log lengkap"]},
      {"id":"report","title":"Reporting","intro":null,"bullets":["Weekly performance review","Monthly recap + forecast","Roadmap action 30 hari","Rekomendasi ad spend: IDR 150.000.000–500.000.000 / bulan"]},
      {"id":"bonus","title":"Bonus","intro":null,"bullets":["Template brief creative","Template weekly review agenda","Checklist LP/WA conversion"]} 
    ]$pkg$::jsonb
  )
on conflict (id) do update set
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  badge_label = excluded.badge_label,
  title = excluded.title,
  package_label = excluded.package_label,
  summary = excluded.summary,
  strikethrough_price = excluded.strikethrough_price,
  price = excluded.price,
  promo_marquee_text = excluded.promo_marquee_text,
  footer_note = excluded.footer_note,
  footer_extra_html = excluded.footer_extra_html,
  show_best_seller = excluded.show_best_seller,
  best_seller_image_path = excluded.best_seller_image_path,
  best_seller_image_url = excluded.best_seller_image_url,
  badge_image_path = excluded.badge_image_path,
  badge_image_url = excluded.badge_image_url,
  promo_countdown_ends_at = excluded.promo_countdown_ends_at,
  footer_countdown_label = excluded.footer_countdown_label,
  show_footer_countdown = excluded.show_footer_countdown,
  spent_budget_min = excluded.spent_budget_min,
  spent_budget_max = excluded.spent_budget_max,
  spent_budget_currency = excluded.spent_budget_currency,
  spent_budget_period = excluded.spent_budget_period,
  fee_percent = excluded.fee_percent,
  sections = excluded.sections,
  updated_at = now();

