-- Seed: agency packages (Paket Ads) based on monthly ad spend.
-- Note: This seed only touches `public.agency_packages` (does not affect wedding packages).

insert into public.agency_packages (
  id, slug, sort_order, is_published,
  badge_label, title, package_label, summary,
  strikethrough_price, price,
  promo_marquee_text, footer_note, footer_extra_html,
  show_best_seller, best_seller_image_path, best_seller_image_url, badge_image_path, badge_image_url,
  promo_countdown_ends_at, footer_countdown_label, show_footer_countdown,
  spent_budget_min, spent_budget_max, spent_budget_currency, spent_budget_period,
  fee_percent,
  sections
) values
  (
    '22222222-2222-4222-8222-000000000001'::uuid,
    'ads_starter',
    0,
    true,
    'Paket Ads',
    'Ads Starter',
    'Ads Starter',
    'Cocok untuk mulai test dan dapat baseline data.',
    'Fee 12%',
    'Fee 10%',
    'Untuk mulai cepat dengan 1 campaign utama + tracking dasar.',
    'Ad spend dibayar langsung ke platform (Meta/TikTok/Google).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    3000000,
    10000000,
    'IDR',
    'per bulan',
    10,
    $pkg$[
      {"id":"setup","title":"Setup & Tracking","intro":"Fondasi supaya hasil bisa diukur.","bullets":["Setup pixel & event dasar","UTM + struktur campaign","Dashboard KPI ringkas"]},
      {"id":"campaign","title":"Campaign","intro":"Satu campaign utama untuk testing.","bullets":["Objective + KPI (CPL/CPA)","1–2 audience utama","Budget harian + rekomendasi"]},
      {"id":"creative","title":"Creative","intro":"Mulai dengan creative yang bisa ditest.","bullets":["Brief 1–2 angle","Copy + CTA","Checklist format creative"]},
      {"id":"reporting","title":"Reporting","intro":null,"bullets":["Update mingguan singkat","Insight + next action"]} 
    ]$pkg$::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000002'::uuid,
    'ads_growth',
    1,
    true,
    'Paket Ads',
    'Ads Growth',
    'Ads Growth',
    'Untuk bisnis yang ingin leads konsisten dan optimasi rutin.',
    'Fee 12%',
    'Fee 10%',
    'Testing creative & audience + optimasi rutin untuk turunkan CPL/CPA.',
    'Ad spend dibayar langsung ke platform (Meta/TikTok/Google).',
    null,
    true,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    10000000,
    30000000,
    'IDR',
    'per bulan',
    10,
    $pkg$[
      {"id":"setup","title":"Setup & Tracking","intro":"Tracking rapi untuk keputusan cepat.","bullets":["Pixel + event lengkap","UTM + naming convention","Dashboard KPI + funnel"]},
      {"id":"campaign","title":"Campaign & Budgeting","intro":"Struktur siap scale bertahap.","bullets":["Cold/warm/retargeting","Alokasi budget + iterasi","Optimasi placement & bid"]},
      {"id":"creative","title":"Creative & Copy","intro":"Creative cadence untuk jaga performa.","bullets":["Angle + hook + CTA","Review creative mingguan","Request revisi terstruktur"]},
      {"id":"optimization","title":"Optimasi","intro":"Improvement berbasis data.","bullets":["A/B test audience/creative","Cek funnel (LP/WA/form)","Kontrol cost per result"]},
      {"id":"reporting","title":"Reporting","intro":null,"bullets":["Laporan mingguan","Ringkasan bulanan","Next action yang jelas"]}
    ]$pkg$::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000003'::uuid,
    'ads_scale',
    2,
    true,
    'Paket Ads',
    'Ads Scale',
    'Ads Scale',
    'Untuk bisnis yang siap scale sampai 100 juta/bulan dengan proses yang rapi.',
    'Fee 12%',
    'Fee 10%',
    'Fokus scale: testing terstruktur, optimasi rutin, dan reporting transparan.',
    'Ad spend dibayar langsung ke platform (Meta/TikTok/Google).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    30000000,
    100000000,
    'IDR',
    'per bulan',
    10,
    $pkg$[
      {"id":"setup","title":"Setup & Tracking","intro":"Tracking dan dashboard yang matang.","bullets":["Pixel + CAPI (opsional)","Event mapping funnel","Dashboard KPI + cohort sederhana"]},
      {"id":"campaign","title":"Campaign & Budgeting","intro":"Struktur scale yang terkontrol.","bullets":["Segmentasi funnel (prospecting/retargeting)","Budgeting + scaling rules","Risk control (cap/guardrail)"]},
      {"id":"creative","title":"Creative & Copy","intro":"Creative pipeline untuk scale.","bullets":["Creative testing plan","Iterasi angle/format","Library insight creative"]},
      {"id":"optimization","title":"Optimasi","intro":"Optimasi multi-variabel.","bullets":["A/B test (creative/audience/LP)","Cek funnel + follow-up","Monitoring harian saat scale"]},
      {"id":"reporting","title":"Reporting","intro":"Lebih detail dan actionable.","bullets":["Weekly performance review","Monthly recap + plan","Catatan eksperimen (what worked)"]},
      {"id":"bonus","title":"Bonus","intro":"Mempercepat eksekusi.","bullets":["Template brief creative","Template WA script sales","Checklist landing page"]} 
    ]$pkg$::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000004'::uuid,
    'ads_enterprise_1',
    3,
    true,
    'Paket Ads',
    'Ads Enterprise',
    'Ads Enterprise',
    'Untuk spent di atas 100 juta/bulan dengan fee lebih efisien.',
    'Fee 10%',
    'Fee 7%',
    'Khusus untuk scale > 100 juta: monitoring lebih rapat + reporting lebih detail.',
    'Ad spend dibayar langsung ke platform (Meta/TikTok/Google).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    100000000,
    250000000,
    'IDR',
    'per bulan',
    7,
    $pkg$[
      {"id":"setup","title":"Tracking & Data","intro":"Lebih ketat untuk scale besar.","bullets":["Audit pixel/event (health-check)","Event mapping per funnel stage","Dashboard KPI + breakdown channel","Alert metrik kritis (spike/drop)"]},
      {"id":"campaign","title":"Scale System","intro":"Scale dengan guardrail dan ritme eksperimen.","bullets":["Scaling rules + kontrol risiko","Eksperimen terjadwal (weekly test plan)","Retargeting & LTV focus","Budget re-allocation berbasis performa"]},
      {"id":"creative","title":"Creative Pipeline","intro":"Cadence creative lebih padat untuk cegah fatigue.","bullets":["Creative testing cadence (lebih rapat)","Library insight + winners/losers","Iterasi cepat berdasarkan data","Guideline hook/angle per persona"]},
      {"id":"optimization","title":"Funnel & CRO","intro":"Bukan hanya ads—fokus ke conversion.","bullets":["Audit landing page/WA/form (bottleneck)","Rekomendasi CRO prioritas","Tracking quality (lead quality) + feedback loop","SOP follow-up sederhana (opsional)"]},
      {"id":"ops","title":"Ops & Monitoring","intro":"Kontrol harian saat scale.","bullets":["Monitoring harian (guardrail)","Checklist issue (tracking/learning/budget)","Incident response (spend spike/drop)"]},
      {"id":"reporting","title":"Reporting","intro":null,"bullets":["Weekly performance review (detail)","Monthly plan + forecast","Catatan eksperimen (what worked/why)","Roadmap 30 hari berikutnya"]},
      {"id":"bonus","title":"Bonus","intro":"Mempercepat kolaborasi.","bullets":["Template brief creative + request revisi","Template dashboard KPI (opsional)","Checklist LP/WA untuk conversion"]} 
    ]$pkg$::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000005'::uuid,
    'ads_enterprise_2',
    4,
    true,
    'Paket Ads',
    'Ads Enterprise+',
    'Ads Enterprise+',
    'Untuk spent 250–500 juta/bulan (multi-campaign) dengan fee 7%.',
    'Fee 10%',
    'Fee 7%',
    'Scale multi-campaign + kontrol kualitas eksekusi harian.',
    'Ad spend dibayar langsung ke platform (Meta/TikTok/Google).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    250000000,
    500000000,
    'IDR',
    'per bulan',
    7,
    $pkg$[
      {"id":"setup","title":"Tracking & Data","intro":"Scale multi-campaign butuh data yang rapi.","bullets":["Audit pixel/event + konsistensi UTM","Dashboard KPI per channel/campaign","Alert metrik kritis (spend/CPA)","Eksperimen log (hypothesis → result)"]},
      {"id":"campaign","title":"Multi-Campaign Management","intro":"Struktur rapi untuk banyak campaign.","bullets":["Segmentasi funnel lebih detail","Budget allocation mingguan + rebalancing","Monitoring harian (guardrail)","Channel expansion (Meta/TikTok/Google) sesuai data"]},
      {"id":"creative","title":"Creative System","intro":"Supply creative harus sejalan dengan scale.","bullets":["Creative cadence terjadwal","Library insight creative (winners)","Angle matrix per persona/offer","Brief & review yang lebih terstruktur"]},
      {"id":"optimization","title":"Optimization","intro":"Efisiensi dan stabilitas hasil.","bullets":["Kontrol CPA/CPL + stabilitas learning","Analisis breakdown audience/placement","Perbaikan funnel bersama tim","Quality feedback loop (sales/CS)"]},
      {"id":"funnel","title":"Funnel & CRO","intro":"Naikkan conversion rate supaya scale lebih efisien.","bullets":["Audit LP/WA/form (prioritas)","Rekomendasi CRO + tracking impact","SOP lead handling (opsional)"]},
      {"id":"reporting","title":"Reporting","intro":null,"bullets":["Weekly + monthly reporting (lebih detail)","Recap eksperimen + keputusan","Action plan 30 hari","Forecast budget & target"]},
      {"id":"bonus","title":"Bonus","intro":"Untuk percepat eksekusi lintas tim.","bullets":["Template brief creative + request revisi","Checklist LP/WA conversion","Template weekly review agenda"]} 
    ]$pkg$::jsonb
  )
on conflict (id) do update set
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  badge_label = excluded.badge_label,
  title = excluded.title,
  package_label = excluded.package_label,
  summary = excluded.summary,
  strikethrough_price = excluded.strikethrough_price,
  price = excluded.price,
  promo_marquee_text = excluded.promo_marquee_text,
  footer_note = excluded.footer_note,
  footer_extra_html = excluded.footer_extra_html,
  show_best_seller = excluded.show_best_seller,
  best_seller_image_path = excluded.best_seller_image_path,
  best_seller_image_url = excluded.best_seller_image_url,
  badge_image_path = excluded.badge_image_path,
  badge_image_url = excluded.badge_image_url,
  promo_countdown_ends_at = excluded.promo_countdown_ends_at,
  footer_countdown_label = excluded.footer_countdown_label,
  show_footer_countdown = excluded.show_footer_countdown,
  spent_budget_min = excluded.spent_budget_min,
  spent_budget_max = excluded.spent_budget_max,
  spent_budget_currency = excluded.spent_budget_currency,
  spent_budget_period = excluded.spent_budget_period,
  fee_percent = excluded.fee_percent,
  sections = excluded.sections,
  updated_at = now();

