-- Seed: agency packages (Paket Content).
-- Note: This seed only touches `public.agency_packages`.

insert into public.agency_packages (
  id, slug, sort_order, is_published,
  badge_label, title, package_label, summary,
  strikethrough_price, price,
  promo_marquee_text, footer_note, footer_extra_html,
  show_best_seller, best_seller_image_path, best_seller_image_url, badge_image_path, badge_image_url,
  promo_countdown_ends_at, footer_countdown_label, show_footer_countdown,
  spent_budget_min, spent_budget_max, spent_budget_currency, spent_budget_period,
  fee_percent,
  sections
) values
  (
    '44444444-4444-4444-8444-000000000001'::uuid,
    'content_starter',
    20,
    true,
    'Paket Content',
    'Content Starter',
    'Content Starter',
    'Untuk mulai konsisten: konten terjadwal + arahan creative.',
    'Rp 2.500.000',
    'Rp 1.500.000',
    'Kalender konten + ide + copy siap posting.',
    'Produksi foto/video bisa dari client atau add-on produksi.',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"plan","title":"Content Plan","intro":"Biar posting nggak random.","bullets":["Kalender konten 4 minggu","Tema & pilar konten","Distribusi format (feed/story/reels)"]},
      {"id":"ideation","title":"Ide & Angle","intro":"Arah creative yang jelas.","bullets":["12 ide konten/bulan","Hook + angle + CTA","Referensi format"]},
      {"id":"copy","title":"Copywriting","intro":null,"bullets":["Caption siap pakai","CTA & keyword sederhana","Hashtag set (opsional)"]},
      {"id":"design","title":"Template (opsional)","intro":null,"bullets":["Template Canva/figma (basic)","Guideline font & warna"]},
      {"id":"review","title":"Review & Revisi","intro":null,"bullets":["Review 1x per minggu","Revisi minor 1x/asset"]}
    ]$pkg$::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000002'::uuid,
    'content_growth',
    21,
    true,
    'Paket Content',
    'Content Growth',
    'Content Growth',
    'Untuk growth organik: konten lebih banyak + creative system.',
    'Rp 4.500.000',
    'Rp 3.000.000',
    'Kalender + script + arahan produksi + evaluasi performa.',
    'Produksi foto/video bisa dari client atau add-on produksi.',
    null,
    true,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"strategy","title":"Content Strategy","intro":"Selaras dengan target bisnis.","bullets":["Persona + positioning ringkas","Pilar konten + objective per pilar","Kalender 4 minggu"]},
      {"id":"ideation","title":"Ide & Script","intro":"Lebih siap produksi.","bullets":["20 ide konten/bulan","Script reels/shorts (10)","Brief visual per konten"]},
      {"id":"copy","title":"Copywriting","intro":null,"bullets":["Caption siap posting","CTA + objection handling","Hashtag set + keyword"]},
      {"id":"creative","title":"Creative System","intro":null,"bullets":["Angle matrix (winners/losers)","Guideline hook & pacing","Template produksi"]},
      {"id":"report","title":"Reporting","intro":null,"bullets":["Review performa mingguan","Recap bulanan + next action"]},
      {"id":"support","title":"Support","intro":null,"bullets":["Revisi minor 2x/asset","Support 5 hari kerja"]}
    ]$pkg$::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000003'::uuid,
    'content_scale',
    22,
    true,
    'Paket Content',
    'Content Scale (Creative Engine)',
    'Content Scale (Creative Engine)',
    'Untuk scale: volume konten tinggi + sistem evaluasi & iterasi.',
    'Rp 8.000.000',
    'Rp 5.500.000',
    'Creative engine: ide → script → review → iterasi yang rapi.',
    'Produksi foto/video bisa dari client atau add-on produksi.',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'per bulan',
    0,
    $pkg$[
      {"id":"strategy","title":"Strategy & System","intro":"Sistem supaya output konsisten.","bullets":["Content operating system","Pilar + angle matrix","Calendar 4 minggu + backlog ide"]},
      {"id":"ideation","title":"Ide & Script","intro":"Siap produksi dan siap iterasi.","bullets":["30 ide konten/bulan","Script reels/shorts (16)","Brief visual per konten"]},
      {"id":"production","title":"Production Support (opsional)","intro":null,"bullets":["Shotlist + checklist produksi","Template subtitle/caption","Guideline editing cepat"]},
      {"id":"review","title":"Creative Review","intro":null,"bullets":["Review 2x per minggu","Iterasi hook/angle/CTA","Library winners/losers"]},
      {"id":"report","title":"Reporting & Insight","intro":null,"bullets":["Weekly insight","Monthly recap + plan","Eksperimen yang terukur"]},
      {"id":"support","title":"Support","intro":null,"bullets":["Revisi minor 3x/asset","Support prioritas"]}
    ]$pkg$::jsonb
  )
on conflict (id) do update set
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  badge_label = excluded.badge_label,
  title = excluded.title,
  package_label = excluded.package_label,
  summary = excluded.summary,
  strikethrough_price = excluded.strikethrough_price,
  price = excluded.price,
  promo_marquee_text = excluded.promo_marquee_text,
  footer_note = excluded.footer_note,
  footer_extra_html = excluded.footer_extra_html,
  show_best_seller = excluded.show_best_seller,
  best_seller_image_path = excluded.best_seller_image_path,
  best_seller_image_url = excluded.best_seller_image_url,
  badge_image_path = excluded.badge_image_path,
  badge_image_url = excluded.badge_image_url,
  promo_countdown_ends_at = excluded.promo_countdown_ends_at,
  footer_countdown_label = excluded.footer_countdown_label,
  show_footer_countdown = excluded.show_footer_countdown,
  spent_budget_min = excluded.spent_budget_min,
  spent_budget_max = excluded.spent_budget_max,
  spent_budget_currency = excluded.spent_budget_currency,
  spent_budget_period = excluded.spent_budget_period,
  fee_percent = excluded.fee_percent,
  sections = excluded.sections,
  updated_at = now();

