-- Seed: agency packages (Paket Landing Page).
-- Note: This seed only touches `public.agency_packages`.

insert into public.agency_packages (
  id, slug, sort_order, is_published,
  badge_label, title, package_label, summary,
  strikethrough_price, price,
  promo_marquee_text, footer_note, footer_extra_html,
  show_best_seller, best_seller_image_path, best_seller_image_url, badge_image_path, badge_image_url,
  promo_countdown_ends_at, footer_countdown_label, show_footer_countdown,
  spent_budget_min, spent_budget_max, spent_budget_currency, spent_budget_period,
  fee_percent,
  sections
) values
  (
    '33333333-3333-4333-8333-000000000001'::uuid,
    'landingpage_starter',
    10,
    true,
    'Paket Landing Page',
    'Landing Page Starter',
    'Landing Page Starter',
    'Cocok untuk 1 produk/offer: cepat rilis, fokus konversi.',
    'Rp 3.500.000',
    'Rp 2.500.000',
    '1 landing page + copy + tracking basic.',
    'Hosting & domain opsional (bisa pakai punya client).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'sekali bayar',
    0,
    $pkg$[
      {"id":"scope","title":"Scope","intro":"1 halaman fokus konversi.","bullets":["1 landing page (single page)","Mobile-first + cepat di-load","Section standar: hero, benefit, social proof, CTA"]},
      {"id":"copy","title":"Copy & Struktur","intro":"Copy padat dan jelas.","bullets":["Copywriting headline + value prop","CTA + objection handling singkat","Struktur konten berdasarkan funnel"]},
      {"id":"design","title":"Design","intro":"Tampilan clean & trust-building.","bullets":["UI sesuai brand","Komponen reusable (section)","Basic image optimization"]},
      {"id":"tracking","title":"Tracking Basic","intro":null,"bullets":["Pixel/tag dasar (Meta/GA)","Event basic (view/lead)","UTM guideline"]},
      {"id":"handover","title":"Handover","intro":null,"bullets":["Dokumentasi singkat","Revisi minor 1x","File/akses diserahkan rapi"]}
    ]$pkg$::jsonb
  ),
  (
    '33333333-3333-4333-8333-000000000002'::uuid,
    'landingpage_growth',
    11,
    true,
    'Paket Landing Page',
    'Landing Page Growth (CRO-ready)',
    'Landing Page Growth (CRO-ready)',
    'Untuk campaign ads: struktur lebih matang + siap A/B test.',
    'Rp 6.000.000',
    'Rp 4.500.000',
    'Landing page CRO-ready + tracking event lebih lengkap.',
    'Hosting & domain opsional (bisa pakai punya client).',
    null,
    true,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'sekali bayar',
    0,
    $pkg$[
      {"id":"scope","title":"Scope","intro":"Landing page siap scale campaign.","bullets":["1 landing page (single page)","Variant section untuk testing (2 opsi)","Speed + SEO basic"]},
      {"id":"copy","title":"Copywriting (lebih dalam)","intro":"Lebih kuat di offer & objection.","bullets":["Angle + hook + proof","FAQ section (anti-drop)","CTA + urgency (tanpa lebay)"]},
      {"id":"tracking","title":"Tracking & Events","intro":"Biar iklan bisa optimasi ke event yang benar.","bullets":["Pixel/GA setup","Event mapping (view/content/lead)","UTM + naming convention"]},
      {"id":"integrations","title":"Integrasi Lead","intro":null,"bullets":["CTA ke WhatsApp/Form","Template WA message (opsional)","Notifikasi email/basic webhook (opsional)"]},
      {"id":"crolist","title":"CRO Checklist","intro":null,"bullets":["Checklist conversion","Heatmap-ready (opsional)","Rencana test 2 minggu (rekomendasi)"]},
      {"id":"handover","title":"Handover & Support","intro":null,"bullets":["Revisi minor 2x","Dokumentasi singkat","Support 7 hari setelah rilis"]}
    ]$pkg$::jsonb
  ),
  (
    '33333333-3333-4333-8333-000000000003'::uuid,
    'landingpage_scale',
    12,
    true,
    'Paket Landing Page',
    'Landing Page Scale (Multi-step)',
    'Landing Page Scale (Multi-step)',
    'Untuk funnel lebih kompleks: multi-step + tracking lebih detail.',
    'Rp 10.000.000',
    'Rp 7.500.000',
    'Multi-step funnel + audit & improvement plan.',
    'Hosting & domain opsional (bisa pakai punya client).',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    'IDR',
    'sekali bayar',
    0,
    $pkg$[
      {"id":"scope","title":"Scope","intro":"Lebih dari sekadar 1 halaman.","bullets":["2–3 step funnel (LP → form/WA → thank you)","Section modular untuk testing","Speed + SEO basic"]},
      {"id":"copy","title":"Copy & Offer System","intro":"Offer dan trust dibangun lebih kuat.","bullets":["Offer breakdown + risk reversal","Social proof layout","FAQ + objection deep dive"]},
      {"id":"tracking","title":"Tracking Advanced","intro":"Supaya analisis funnel jelas.","bullets":["Event mapping per step","Conversion API (opsional)","Dashboard KPI basic (opsional)"]},
      {"id":"ux","title":"UX & Form/WA Flow","intro":null,"bullets":["Form flow yang singkat","WA flow + quick replies (opsional)","Reduce friction points"]},
      {"id":"crosprint","title":"CRO Sprint (Plan)","intro":"Rencana improvement berbasis data.","bullets":["Audit awal (before)","Daftar eksperimen prioritas","Roadmap test 30 hari"]},
      {"id":"handover","title":"Handover","intro":null,"bullets":["Revisi minor 3x","Dokumentasi + akses","Support 14 hari setelah rilis"]}
    ]$pkg$::jsonb
  )
on conflict (id) do update set
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  badge_label = excluded.badge_label,
  title = excluded.title,
  package_label = excluded.package_label,
  summary = excluded.summary,
  strikethrough_price = excluded.strikethrough_price,
  price = excluded.price,
  promo_marquee_text = excluded.promo_marquee_text,
  footer_note = excluded.footer_note,
  footer_extra_html = excluded.footer_extra_html,
  show_best_seller = excluded.show_best_seller,
  best_seller_image_path = excluded.best_seller_image_path,
  best_seller_image_url = excluded.best_seller_image_url,
  badge_image_path = excluded.badge_image_path,
  badge_image_url = excluded.badge_image_url,
  promo_countdown_ends_at = excluded.promo_countdown_ends_at,
  footer_countdown_label = excluded.footer_countdown_label,
  show_footer_countdown = excluded.show_footer_countdown,
  spent_budget_min = excluded.spent_budget_min,
  spent_budget_max = excluded.spent_budget_max,
  spent_budget_currency = excluded.spent_budget_currency,
  spent_budget_period = excluded.spent_budget_period,
  fee_percent = excluded.fee_percent,
  sections = excluded.sections,
  updated_at = now();

